development:
  adapter: postgresql
  encoding: unicode
  database: hunger_development
  pool: 5
  username: evobersi
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: hunger_test
  pool: 5
  username: evobersi
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: hunger_production
  pool: 5
  username: hunger
  password:
